project:
  type: website
  output-dir: docs

website:
  title: "Advice-Taking Metaanalysis"
  description: "Progress and report on advice-taking metaanalysis work"
  site-url: "https://jhelmer3.github.io/advice-taking-metaanalysis/"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Reports"
        menu:
          - Reports/metaanalysis_report.qmd
          - Reports/trihurdle_report.qmd 
          - Reports/trihurdle-metaanalysis_report.qmd
    tools:
      - icon: github
        href: https://github.com/jhelmer3/advice-taking-metaanalysis
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
