---
title: "Advice-Taking Metaanalysis"
subtitle: "Analysis Report"
date: last-modified
author: "Jessica Helmer"
---

## Overview

This site is my log of work on converting the [Himmelstein (2022)](https://doi.org/10.1016/j.jmp.2022.102695) advice-taking dual-hurdle model to better model advice-taking in a metaanalytic context. 

:::: {.columns .v-center-container}
::: {.column width="70%"}
### Metaanalysis Model

First, I converted the [Himmelstein (2022)](https://doi.org/10.1016/j.jmp.2022.102695) model from a two-level cross-classified model, with responses cross-classified within judges and items, into a three-level cross-classified model, with responses cross-classified within judges and items and then nested within studies.

One key initial finding from this metaanalysis is that some studies have a high proportion of Weight of Advice (WOA) values of exactly 0.5. To address this, we explored adding a third hurdle to the model.
:::

::: {.column width="5%"}
:::

::: {.column width="25%" .l-center-container}
[Metaanalysis](/Reports/metaanalysis_report.qmd){.btn .btn-outline-primary .btn role="button"}
:::
::::

:::: {.columns .v-center-container}
::: {.column width="70%"}
### Tri-Hurdle Model

With just one study that was high on 0.5s, we modified the original model to include an additional Midpoint hurdle.
:::

::: {.column width="5%"}
:::

::: {.column width="25%" .l-center-container}
[Tri-Hurdle](/Reports/trihurdle_report.qmd){.btn .btn-outline-primary .btn role="button"}
:::
::::

:::: {.columns .v-center-container}
::: {.column width="70%"}
### Tri-Hurdle Metaanalysis Model

With that model successfully estimated, we then merged the tri-hurdle and metaanalytic model frameworks.
:::

::: {.column width="5%"}
:::

::: {.column width="25%" .l-center-container}
[Tri-Hurdle Metaanalysis](/Reports/trihurdle-metaanalysis_report.qmd){.btn .btn-outline-primary .btn role="button"}
:::
::::



