---
title: "Methods"
author: Jess Helmer
date: last-modified
execute:
  echo: false
format:
  html:
    include-in-header:
      text: |
        <script>
        MathJax = {
          tex: {
            macros: {
              note: ["\\textcolor{gray}{\\scriptstyle\\text{#1}}", 1]
            }
          }
        };
        </script>
---

```{r}
#| eval: false
library(targets)

tar_load(c(study_counts), 
         store = here::here("_targets"))
```


### Data

For this work, we used data already collected for a different metaanlaysis focused on gender effects in advice-taking. More details on the methods of data collection and the other metaanalysis are in (Kausel et al., 2024). This full dataset had \[over 300,000\] observations of advice-taking trials from `N_people` people on `N_items` different items from `N_studies` studies.

All of the studies included in the dataset came from JAS designs, meaning participants were asked for both their initial and final judgements. Along with the values of the advice given on each trial, we could calculate WOA for each observations. We removed cases that had missing values for either the initial and final judgements. We also removed cases that happened to have provided exactly the same initial judgement as the advice ($J_1 = A$), meaning the denominator of the WOA calculation was zero^[Some JAS studies use crowd aggregates as advice, right? Probably would be rare given the exact equality, but might this disproportionately remove higher-accuracy people? Because higher-accuracy people might tend to give judgements closer to the WoC?]. 

The data also included multiple potential predictors of advice-taking at the trial-, person-, and study-level (no predictors varied at the item-level). The only trial-level predictor we included was advice distance: the distance between the judge's initial judgement and the advice, calculated as $| J_1 - A |$. At the person-level, we included participant age and gender as predictors. We included five study-level predictors. We included an indicator for whether the study used "almanac" items (i.e., asking for judgements on facts about the world, like the distance between two cities), and an indicator for studies using "future" items (i.e., asking for predictions about the future, like the price of gas in three months). We also included indicators for if the advice given was said to come from an expert, whether the study's data was collected from a student population, and whether the study offered an incentive to participants. We removed observations with missing data on any of the predictors, leaving a dataset with \[over 200,000\] observations of advice-taking trials from `N_people` people on `N_items` different items from `N_studies` studies.

### Dual-Hurdle Metaanalysis Model

To conduct this metaanalysis, we extended Himmelstein's (2023) dual-hurdle model into a metaanalytic model by adding random effects to capture study-level variation. In this notation, $i$ indexes each JAS trial, $j$ indexes each person, $k$ indexes each item, and $s$ indexes each study. The unconditional form of the model is:

{{< include ../models/notation/dual-hurdle_metaanalysis_unconditional_centered.qmd >}}

Adding in a matrix of predictors to the model, the form is:

{{< include ../models/notation/dual-hurdle_metaanalysis_conditional_centered.qmd >}}

where $\bf{b}$ is a vector of priors scaled to each predictor and is set to $3$ for binary predictors.

We estimated the conditional model with Bayesian estimate in Stan, using the `cmdstanr` package to interface between R and Stan, with 1,000 warmup iterations and 2,500 sampling iterations on each of four chains. We examined model convergence via $\hat{R}$ values and some visual inspection of trace and tracerank plots. We examined the model performance by comparing the model's posterior predictive distribution to the distribution of the observed data.

### Transition From Dual- to Tri-Hurdle


### Tri-Hurdle Model

#### Estimation on a Single Study

We then extended the model to include an additional hurdle for WOA values of exactly 0.5. First, we implemented this by adding the additional hurdle on a single study's data (stepping back from the metaanalytic context). With just person- and item-level varying effects, the form of this model is: 

{{< include ../models/notation/tri-hurdle_centered.qmd >}}

where the $M$ subscript represents parameters corresponding to the new midpoint hurdle. We again estimated this model in Stan.

#### Tri-Hurdle Metaanalysis Model

We then converted the tri-hurdle model into a metaanalysis model by adding varying effects at the study level. The conditional form of the model is:

{{< include ../models/notation/tri-hurdle_metaanalysis_conditional_centered.qmd >}}

where $\bf{b}$ once again is a vector of priors scaled to each predictor and is set to $3$ for binary predictors. We estimated this model in Stan and examined diagnostics. 





